# Generated by Django 5.2.5 on 2025-09-04 18:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recibos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_realizadas', to=settings.AUTH_USER_MODEL)),
                ('recibo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transferencia', to='recibos.recibo')),
            ],
        ),
    ]
